Added hearts and spades icons for minimap
Terasology/LightAndShadowResources pull request #31
Opened 2019-08-15 23:16 UTC by darshan3

2019-08-18 16:02 UTC, iaronaraujo approved these changes

2019-08-20 18:26 UTC, skaldarnar approved these changes

2019-08-20 18:40 UTC, skaldarnar requested changes
Wait - can't you use the icons that are already there? 

There is at least [`assets/textures/items.png`](
https://github.com/Terasology/LightAndShadowResources/blob/master/assets/textures/items.png) which seems to contain the heart and spades icons, and the corresponding atlas at [`assets/atlas/items.atlas`](https://github.com/Terasology/LightAndShadowResources/blob/MinimapIcons/assets/atlas/items.atlas). 

I don't think this addition is necessary.

2020-05-22 18:08 UTC, jdrueckert approved these changes

2020-05-22 18:08 UTC, merged