Health bar UI size increase
Terasology/LightAndShadowResources pull request #41
Opened 2020-07-03 11:02 UTC by stefaniamak

# Changes

Changes the size of the bar to all 3 types of icons for the bar. The numbers are symbolic.

# References

### Please ignore the Quickslot being over the health bar. 
__The quickslot is going to be placed at the right part of the screen, through another repository and PR.__

## Each Change close up
<img width="217" alt="1" src="https://user-images.githubusercontent.com/48293545/86462644-92f99280-bd34-11ea-8f9b-5882e3034c3f.png">
<img width="219" alt="2b" src="https://user-images.githubusercontent.com/48293545/86462856-056a7280-bd35-11ea-901e-62565d22ef08.png">
<img width="223" alt="Screenshot_5" src="https://user-images.githubusercontent.com/48293545/86462661-9ab93700-bd34-11ea-86ff-e6171a830707.png">

## Whole screen

<img width="660" alt="Screenshot_6" src="https://user-images.githubusercontent.com/48293545/86462908-25019b00-bd35-11ea-8111-390c22980d4b.png">

2020-07-06 17:31 UTC, stefaniamak commented
Related to https://github.com/Terasology/LightAndShadow/pull/124

2020-07-07 08:49 UTC, jdrueckert requested changes
The test assets sneaked into this PR. Please remove them, then we can merge this.

2020-07-07 08:51 UTC, stefaniamak commented
Snap, and I checked if the were any extra code... On it!

2020-07-08 18:30 UTC, jdrueckert approved these changes

2020-07-08 18:30 UTC, merged