Health bar skin files organization
Terasology/LightAndShadowResources pull request #42
Opened 2020-07-09 14:38 UTC by stefaniamak

Related PR
* https://github.com/Terasology/LightAndShadow/pull/124

# Result

We now have 1 skin file (`healthHud.skin`) to change the size of the icons within one file, which is located within the LightAndShadow module. The rest 3 skin files located in the LightAndShadowResources module inherit the size from the mentioned skin file.

## Changes

* Deleted all size attributes within the 3 skin files within LightAndShadowResources
* Made them inherit the size within the LightAndShadow skin about the health bar.

The file from which they inherit from can be found through this draft PR: https://github.com/Terasology/LightAndShadow/pull/124.

## How to test

Make sure you have set up the https://github.com/Terasology/LightAndShadow/pull/124 as well.

* Start a LaS game (both old or new game file works fine)
* Check the size of the health bar
* You can enter a team by clicking one of the two (black or red) boxes, to check the size of the other teams' icon size.

Extra: you can go ahead and change the size number placed within the `healthHud.skin` from the lines:
```json
"icon": {
    "fixed-width": 30,
    "fixed-height": 30
}
```
to make extra sure.

2020-07-10 21:05 UTC, jdrueckert commented
Uhmm... Maybe I misunderstood the PR description, but...
> The rest 3 skin files located in the LightAndShadowResources module inherit the size from the mentioned skin file.
Isn't that exactly the LASR -> LAS dependency we didn't want to have? :thinking:
Thought we're going for LAS -> LASR... but maybe I'm mixing something up?

2020-07-11 09:04 UTC, stefaniamak commented
>  that exactly the LASR -> LAS dependency we didn't want to have? 🤔

Yes, it is.. Skaldarnar mentioned this as well. I plan on moving all health realared UI/skin files within LaSR.

2020-07-12 18:17 UTC, jdrueckert requested changes
Guess these changes were lost when moving the files, I believe you had them integrated earlier in the LAS PR (124).
While we're on it, let's also rename `healthHud.skin` to `healthBase.skin` to make it clear, that this is the base for red, black and white to inherit from.

2020-07-12 18:17 UTC, jdrueckert commented on assets/skins/healthHud.skin
> +    }
can be removed as healthHud is only used as a base to inherit from

2020-07-12 18:17 UTC, jdrueckert commented on assets/skins/healthBlack.skin
>      "elements": {
can be removed as it's inherited from healthHud

2020-07-12 18:17 UTC, jdrueckert commented on assets/skins/healthRed.skin
>      "elements": {
can be removed as it's inherited from healthHud

2020-07-12 18:17 UTC, jdrueckert commented on assets/skins/healthWhite.skin
>      "elements": {
can be removed as it's inherited from healthHud

2020-07-12 21:11 UTC, merged