Disabled mode for restart button
Terasology/LightAndShadowResources pull request #60
Opened 2020-09-10 15:25 UTC by ahv15

### Contains
Part of  https://github.com/Terasology/LightAndShadow/pull/161 and adds the disabled mode to the UIButton which has to be used for the restart button.

### How to test
Join a single player or multiplayer game and when the game is over, for the first 10 seconds the disabled mode of the refresh button will be visible.

### Outstanding before merging
- [x] Disabled mode for UIButton.

2020-09-15 11:45 UTC, stefaniamak requested changes
Tested it out alongside https://github.com/Terasology/LightAndShadow/pull/161#pullrequestreview-488594210 and it works as expected 👍 

I just want to suggest you making the letters slightly darker, so change the "E8E8E8" part of the color, with a darker grey HEX number :)

2020-09-15 11:47 UTC, stefaniamak commented
_Also another note about making PRs:_ it's always nice to show a screenshot of your changes (especially when it is a UI change), so when reviewing we can be sure we saw what we expected to see!

2020-09-19 13:11 UTC, ahv15 commented
![Screenshot (448)](https://user-images.githubusercontent.com/52852877/93668026-9127ab80-faa7-11ea-87c9-e34afb8c760b.png)
@stefaniamak  Is this color a bit too dark or is it fine?

2020-09-23 06:44 UTC, stefaniamak commented
I think it looks cool, yes!

2020-09-23 07:18 UTC, ahv15 commented
Done.

2020-09-24 21:30 UTC, stefaniamak approved these changes
Tested it and works as expected 👍 I am merging it.

2020-09-24 21:30 UTC, merged